### ISSUE TITLE
No Source files found at: scripts/temp/tmp1/similarityMatrix

### ISSUE THREAD

**Issue by KlwntSingh** [pferrel/solr-recommender#11]
I get this error when i run the code from eclipse

Exception in thread "main" java.io.IOException: No Source files found at: scripts/temp/tmp1/similarityMatrix
	at finderbots.recommenders.hadoop.WriteDRMsToSolr.getTaps(WriteDRMsToSolr.java:149)
	at finderbots.recommenders.hadoop.WriteDRMsToSolr.joinDRMsWriteToSolr(WriteDRMsToSolr.java:79)
	at finderbots.recommenders.hadoop.WriteToSolrJob.run(WriteToSolrJob.java:105)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at finderbots.recommenders.hadoop.RecommenderUpdateJob.run(RecommenderUpdateJob.java:172)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at finderbots.recommenders.hadoop.RecommenderUpdateJob.main(RecommenderUpdateJob.java:275)

**Comment by KlwntSingh** [comment]
need to change the path in arguments which are passed to WriteDRMsToSolrJob. It will solve the problem
